user  nginx;
worker_processes  auto;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile        on;

    upstream users_service {
        server users:8081;
    }

    upstream petpal_service {
        server petpal:8080;
    }

    server {
        listen 80;

        # http://localhost:<GATEWAY_PORT>/users/api/users -> users:8081/api/users
        location /users/ {
            proxy_pass http://users_service/;
            include /etc/nginx/proxy_headers.conf;
            proxy_connect_timeout 5s;
            proxy_send_timeout 30s;
            proxy_read_timeout 30s;
        }

        # http://localhost:<GATEWAY_PORT>/petpal/api/owners -> petpal:8080/api/owners
        location /petpal/ {
            proxy_pass http://petpal_service/;
            include /etc/nginx/proxy_headers.conf;
            proxy_connect_timeout 5s;
            proxy_send_timeout 30s;
            proxy_read_timeout 30s;
        }
    }
}
